/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsSlugRouteImport } from './routes/collections_.$slug'
import { Route as CollectionsCategorySlugProductIdRouteImport } from './routes/collections_.$categorySlug.$productId'

const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections_/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCategorySlugProductIdRoute =
  CollectionsCategorySlugProductIdRouteImport.update({
    id: '/collections_/$categorySlug/$productId',
    path: '/collections/$categorySlug/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/collections/$categorySlug/$productId': typeof CollectionsCategorySlugProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/collections/$categorySlug/$productId': typeof CollectionsCategorySlugProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/collections_/$slug': typeof CollectionsSlugRoute
  '/collections_/$categorySlug/$productId': typeof CollectionsCategorySlugProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections'
    | '/collections/$slug'
    | '/collections/$categorySlug/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections'
    | '/collections/$slug'
    | '/collections/$categorySlug/$productId'
  id:
    | '__root__'
    | '/'
    | '/collections'
    | '/collections_/$slug'
    | '/collections_/$categorySlug/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsRoute: typeof CollectionsRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  CollectionsCategorySlugProductIdRoute: typeof CollectionsCategorySlugProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections_/$slug': {
      id: '/collections_/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections_/$categorySlug/$productId': {
      id: '/collections_/$categorySlug/$productId'
      path: '/collections/$categorySlug/$productId'
      fullPath: '/collections/$categorySlug/$productId'
      preLoaderRoute: typeof CollectionsCategorySlugProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsRoute: CollectionsRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  CollectionsCategorySlugProductIdRoute: CollectionsCategorySlugProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
